# Import necessary functions
from finrl.plot import backtest_stats, backtest_plot, get_daily_return, get_baseline

# Assume df_account_value_ppo is the DataFrame of portfolio values over time
# generated by your PPO model, and df_actions_ppo is the DataFrame of actions.

# Calculate and display backtest statistics
backtest_result = backtest_stats(df_account_value_ppo)
print(backtest_result)

# Plot the portfolio value over time
backtest_plot(df_account_value_ppo, df_actions_ppo)

# Calculate daily returns
daily_returns = get_daily_return(df_account_value_ppo)
print(daily_returns.head())

# Assume stock_prices is a DataFrame containing the stock prices over time.
# Calculate and display baseline performance for comparison
baseline_result = get_baseline(stock_prices)
print(baseline_result)
